version: '3.8'

services:
  arlmt-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arlmt-dev
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
    environment:
      - DISPLAY=${DISPLAY}
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app/src
    runtime: nvidia
    stdin_open: true
    tty: true
    command: /bin/bash
