# QLoRA Training Configuration for ARLMT

model:
  base_model: "liuhaotian/llava-v1.5-7b"
  model_type: "llava"
  torch_dtype: "float16"
  device_map: "auto"

qlora:
  r: 64
  lora_alpha: 16
  target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  use_rslora: true
  use_dora: false

training:
  output_dir: "./outputs/qlora_training"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  save_total_limit: 3
  evaluation_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  report_to: "tensorboard"
  dataloader_num_workers: 4
  remove_unused_columns: false
  fp16: true
  gradient_checkpointing: true
  deepspeed: null

data:
  train_data_path: "./data/medical_qa_train.json"
  eval_data_path: "./data/medical_qa_eval.json"
  max_length: 2048
  image_size: 336
  image_aspect_ratio: "pad"

logging:
  log_level: "INFO"
  log_file: "./logs/training.log"
  tensorboard_dir: "./logs/tensorboard"

checkpointing:
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 3
  resume_from_checkpoint: null
